### PR TITLE
Fix gearscore color

### PR DESCRIPTION
**Pull request by ForestJ316**
Green and Blue was switched

### CODE REVIEW

**Comment by anzz1** [comment]
Did this https://github.com/anzz1/TacoTip/pull/5 fix it ? Because from the testing I did a month ago it seemed that the colors for total gearscores were correct, but I didn't check the individual items so a simple typo ended up shifting the result left making the values wrong like this: red=item level , green=red, blue=green , blue=skipped completely.

**Comment by ForestJ316** [comment]
Yeah it's correct color now. When I was editing the tooltip for myself I just noticed that vars were switched so thought it was flipped but now I look closer the result is exactly the same, just it's not intuitive.

Blue is assigned to Green values and vice versa:
https://github.com/anzz1/TacoTip/blob/babc3143e73b03807e66d5bee36d23a37649e1fd/gearscore.lua#L94-L99
but then Blue is passed values that Blue should use, just key is called Green, same for Green -> Blue:
https://github.com/anzz1/TacoTip/blob/babc3143e73b03807e66d5bee36d23a37649e1fd/gearscore.lua#L159-L164

So I guess in the end this PR is just clean var assignments so to speak

**Comment by anzz1** [comment]
Yeah the original GearScoreLite where the tables for the scores and color values are from was definitely among some of the best carbonara I ever tasted. The original version actually switched the colors around multiple times and finally output them in the wrong order (what was named green was output as blue, and vice-versa), but the thing is that the result is the color palette and calculations everyone grew to know by heart. So while un-spaghettifying it I had to be careful to not actually change the result. 

That's why it still looks pretty much like your friday spaghetti night as I didn't want to change anything. 

One thing is that, as has been reported, the individual item scores for hunter weapons are wrong, as the calculation for the total score applies a score multiplier for the MH/OH/ranged wep for hunters, but this doesn't happen in the individual itemscore calculation, only after it. This is how it originally was too, so like everything else, I didn't change it.

But maybe that's something I should fix though? As it really is pretty stupid and unintuitive that the total score and individual item scores for hunters don't match.

**Comment by ForestJ316** [comment]
It can be done. But you would need to decide how u want to display it. Give players the option to toggle it on/off? Do you show it only if the "player" unit is hunter, or do you show it for all players (in case they want to see how much it would benefit their alt hunter etc.)? What do you do about item links in chat (here is where the toggle would be useful I guess)? Also would want to change GearScore text on tooltip to HunterScore or perhaps it's better to just add an extra line below GearScore to display HunterScore.
If I remember correctly, the version I was using in 3.3.5a just added HunterScore on a new line after GearScore if I was a hunter, on other classes I wouldn't see it. Perhaps it can be done in same way just with a toggle option in settings, so in case players that are not hunters want to see HunterScore, they can toggle it on.

**Comment by anzz1** [comment]
HunterScore for individual items added in v0.2.9 https://github.com/anzz1/TacoTip/commit/b5f24b80f011e68c5310d1dd4fb3b3e5c0636b1c

By default it always shows if you are a Hunter or inspecting a Hunter. And if not, can show it by pressing a modifier key like CTRL/SHIFT/ALT.

There is also an option to always show it, but it's not currently in the options menu. 
You can set it manually if you like by entering in chat:
`/run TacoTipConfig.show_gs_items_hs = true`

**Pull request closed without merging**
